# Generated by Django 3.1.2 on 2020-10-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50, verbose_name='Mesaj Alanı')),
                ('log_date', models.DateTimeField(verbose_name="Log'un tarihi")),
            ],
        ),
    ]
